name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
      branches:
        - staging
jobs:
    Tests:
      name: Tests # название конктретной работы в pipeline
      runs-on: ubuntu-latest
      steps:
        - name: Checkout # клонируем репозиторый
          uses: actions/checkout@v2

        # - name: Install dependencies
          # run: npm install --force # устанавливаем зависимости

        - name: Test
          run: npm test # запускаем скрипт тестами

    Deploy-Preview:
      runs-on: ubuntu-latest
      needs: Tests
      steps:
        - uses: actions/checkout@v2
        - name: Install Vercel CLI
          run: npm install --global vercel@latest
        - name: Pull Vercel Environment Information
          run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        - name: Build Project Artifacts
          run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        - name: Deploy Project Artifacts to Vercel
          run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}